name: Python Lint

on:
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        python-version: ["3.13"]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          pip install pylint flake8

      - name: Run pylint
        run: |
          pylint \
            --disable=C0114,C0115,C0116,W0622 \
            --max-line-length=128 \
            --output-format=colorized \
            $(git ls-files '*.py')

      - name: Run flake8
        run: |
          flake8 \
            --max-line-length=128 \
